import { chromium } from 'playwright';
const b=await chromium.launch(); const p=await (await b.newContext()).newPage();
const log=[]; p.on('pageerror',e=>log.push(e.message));
const man = await p.goto('http://localhost:5199/manifest.webmanifest'); console.log('manifest status:', man.status());
const sw = await p.goto('http://localhost:5199/sw.js'); console.log('sw.js status:', sw.status());
const ic = await p.goto('http://localhost:5199/icons/icon-512.png'); console.log('icon-512 status:', ic.status());
await p.goto('http://localhost:5199/',{waitUntil:'networkidle'}); await p.waitForTimeout(1500);
const reg = await p.evaluate(async()=>{ const r=await navigator.serviceWorker.getRegistration(); return !!r; });
const hasManifestLink = await p.evaluate(()=>!!document.querySelector('link[rel="manifest"]'));
console.log('service worker registered:', reg, '| manifest linked:', hasManifestLink, '| ERR:', log.length?log.join('|'):'none');
await b.close();
